spring:
    application:
        name: mg-canoe
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: test
        url: jdbc:mariadb://127.0.0.1:3308/canoe_db?allowMultiQueries=true&application_name=crm
#        url: jdbc:mysql://localhost:3306/canoe_db?application_name=crm&allowMultiQueries=true
#        url: jdbc:mariadb://10.100.248.11:3307/crm_global_db?application_name=crm
        username: root
        password: wst372922
#        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.mariadb.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
#    rabbitmq:
#        host: 10.100.248.4
#        port:  5672
#        username: guest
#        password: guest
    sleuth:
      enabled: true
      http:
        legacy:
          enabled: true
    redis:
      #database: 2
      host: 127.0.0.1
      #password: 12345678
    thymeleaf:
      prefix: classpath:/web/
      suffix: .html
      mode: LEGACYHTML5
      encoding: utf-8
      cache: false

    messages:
        basename: i18n/messages
    mvc:
      static-path-pattern: /static/**
    resources:
      static-locations: classpath:/web/static
    jmx:
      enabled: false
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 0
            max-request-size: 50MB
            max-file-size: 50MB
            location: upload

logging:
  level:
     com.hworld.canoe : debug
     com.dy.springboot.server.mapper: debug

sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    enabled: false


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.hworld.canoe.framework.db.canoedb.entity
  xmlLocation: classpath:/mybatis-mappers/*
  mapper-locations: classpath:/mybatis-mappers/*
  basepackage: com.hworld.canoe.framework.db.canoedb.mapper
#mybatis:
#    basepackage: com.hworld.crm.member.db
#    xmlLocation: classpath:mapper/**/*.xml
#    mapper-locations: "classpath*:mapper/*.xml"

server:
    port: 80


#eureka:
#    instance:
#        statusPageUrlPath: /actuator/info
#        healthCheckUrlPath: /actuator/health
#        # docker 部署开启
#        prefer-ip-address: true
##        ip-address: 127.0.0.1
#    client:
#        serviceUrl:
##            defaultZone: http://localhost:8761/eureka/
#                    # docker 部署开启
#            defaultZone: http://10.100.248.5:8761/eureka/
## 必须配置
#feign:
#  httpclient:
#    enabled: false
#  okhttp:
#    enabled: true
#
#ribbon:
#  eureka:
#    enabled: true
#  ReadTimeout: 100000
#  ConnectTimeout: 100000
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 1
#  OkToRetryOnAllOperations: false
#
#hystrix:
#  threadpool:
#    default:
#      coreSize: 1000 ##并发执行的最大线程数，默认10
#      maxQueueSize: 1000 ##BlockingQueue的最大队列数
#      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 110000


# 配置swagger
swagger:
    enabled: true
    base-package: com.hworld.canoe.rest
    title: 皮划艇项目
    version: 1.0.0.SNAPSHOT
    description: 皮划艇项目
    contact:
        name: mg



#redis-cache 相关
#redis:
#    pool:
#         maxActive: 300
#         maxIdle: 100
#         maxWait: 1000
#    host: 10.105.17.238
#    port:  6379
#    password: 12345678
#    timeout: 2000
#    # 服务或应用名
#    sysName: mg-crm-member
#    enable: true
#    database: 2

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
      limit: 100
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 10.105.17.238
      port: 6379
      password: 12345678
      database: 2
      
      
      
      
      
      